name: Deploy Backend to AWS EC2

# main 브랜치에 push 될 때마다 이 스크립트가 실행됩니다!
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # 1. 깃허브에 있는 최신 백엔드 코드와 도커 설정파일을 AWS 서버로 복사해서 보냅니다.
      - name: Copy Backend Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: "server/,docker-compose.yml"
          target: "/home/ubuntu/my-traffic-judge"

      # 2. AWS 서버에 원격 접속해서 예전 도커를 끄고, 최신 코드로 도커를 다시 켭니다!
      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/my-traffic-judge
            docker-compose down
            docker-compose up -d --build